# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Max's Blog
subtitle: 邁向全端的後端工程師
author: Max Lin
language: zh-TW
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://maxlin0523.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Max's Blog | 邁向全端之路
email: happytieu@gmail.com
description: 邁向全端的後端工程師
keyword: 前端,後端,全端,程式開發,後端開發,後端工程師,C#,ASP.NET,.NET Core,.NET Framework

## Home封面
header-img: https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Feeb2a157-aaf5-469e-8662-7442c36a1a0f%2FUntitled.png?table=block&id=ebe1a59c-240f-4051-8ad1-34ad1d959ce6&spaceId=59d38cce-92ff-4673-85e7-4a3082371d03&width=2850&userId=6c123588-4407-4a28-9aae-2bb53ad5b808&cache=v2

# 封面右下角標籤
signature: true #show signature
signature-img: 

# RSS Hub
feed:
    type: atom
    path: atom.xml
    limit: 20
    hub:
    content:
    content_limit:
    content_limit_delim: ' '

RSS: true

# 自訂連結
github_username: maxlin0523
medium_username: max-lin

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
# disqus_username:

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
# 個資簡介
sidebar-about-description: "Hi, I'm Max, also a backend engineer."
# 大頭貼
sidebar-avatar: https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fe989c118-0e35-46d0-8180-3b81e1951d93%2F94E6B1BC-695F-450D-93D8-8880E424A8F4.jpeg?table=block&id=2f192d56-e330-44bc-97b1-0857518471cc&spaceId=59d38cce-92ff-4673-85e7-4a3082371d03&width=4270&userId=6c123588-4407-4a28-9aae-2bb53ad5b808&cache=v2    
widgets:
- short-about
- recent-posts
- friends-blog
- videos-blog
- featured-tags
# - archive
# - category

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## 好部落
friends: [
    {
        title: "阮一峰的网络日志",
        href: "https://www.ruanyifeng.com/blog/"
    },{
        title: "John Wu's Blog",
        href: "https://blog.johnwu.cc/"
    },{
        title: "Jed's blog",
        href: "https://jed1978.github.io/"
    },{
        title: "Blackie's Failed Notes",
        href: "https://blackie1019.gitlab.io/"
    },{
        title: "安德魯的部落格",
        href: "https://columns.chicken-house.net/categories/"
    },{
        title: "石頭的coding之路",
        href: "https://isdaniel.github.io/"
    }
]

## 好視頻
videos: [
    {
        title: "Anduin Xue (.NET)",
        href: "https://www.youtube.com/channel/UCe1nKo3WGGzyTgDqmTdZzlA/featured"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: beantech

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/maxlin0523/maxlin0523.github.io.git
  branch: master
 #  message: Max's Blog